In [2]:
import numpy as np
import pandas as pd
import os

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix, roc_curve, auc

from nltk.tokenize import wordpunct_tokenize
#, sent_tokenize, word_tokenize 
from nltk.stem import PorterStemmer

ModuleNotFoundError: No module named 'pandas'

In [ ]:

#creating the traning set data frame 
articles_set = pd.DataFrame(columns = ["article", "topic"])

In [ ]:

#creating a new Porter stemmer object
Porter = PorterStemmer()
def stemSentence(sentence):
    #divide the sting into a list of words
    #useing the 
    token_words = wordpunct_tokenize(sentence)
    #create a list to store the words afterstemmiing them
    stem_sentence=[]
    #go throgh all the words in the sentence 
    for word in token_words:
        #addint the stemed word to the stem_sentence
        stem_sentence.append(Porter.stem(word))
        #adding a space after it
        #(so the words will have spaces between them in the sentence)
        stem_sentence.append(" ")
    #turn the list into a sentence and return it 
    return "".join(stem_sentence)

In [ ]:
#reading the traning articles and adding them to the traning set

#reading the folders(topic) in the training folder 
articles = os.listdir("articles") 

#for each topic folder in the traning folder
for topic in articles :
    #reading all the files(articles) in this topic
    topic_articles = os.listdir("articles"+"/"+topic)

    #go throgh each article in this topic folder
    for article in topic_articles:
        #opening this article txt file
        file = open("articles/"+topic+"/"+article,'r', encoding='utf-8')
        #reading to get the artical as a string
        file_string = file.read()
        #to stem the 
        file_string = stemSentence(file_string)

        #to add a new row to the datafram using concat
        #first we creat the row
        new_row = [file_string, topic]
        #then we create a dataframe with only that row
        new_df = pd.DataFrame([new_row], columns = ["article", "topic"])
        #then concat it with the traning set data frame 
        articles_set = pd.concat([articles_set, new_df], ignore_index = True)

        #closing the file
        file.close()


#training_set.to_string()
articles_set

article       topic
0    ' hero ' help no . 3 michigan past illinoi to ...      sports
1    ' ladi day ' at the dp world tour championship...      sports
2    aaron rodger take blame for miss throw as pack...      sports
3    arsen boss arteta delight by white ’ s england...      sports
4    attack pair ali and afif spearhead qatar world...      sports
..                                                 ...         ...
149  war in ukrain : what are tactic nuclear weapon...  technology
150  whi doe the govern invest in clean energi inno...  technology
151  yale scientist discov that light acceler condu...  technology
152  ‘ what you don ’ t get in classroom ’: cyberse...  technology
153  “ erasur ” – new discoveri could be the key to...  technology

[154 rows x 2 columns]

In [ ]:
vectorizer = CountVectorizer(stop_words='english')
#creating a document-term matrix and getting the vocab
all_features = vectorizer.fit_transform(articles_set.article)
#number of columns = total number of words in the whole traning set
#number of rows = number of artical in the traning set
print(all_features.shape)
all_features.toarray()

(154, 9234)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
vectorizer.vocabulary_

{'hero': 3937,
 'help': 3921,
 'michigan': 5377,
 'past': 6174,
 'illinoi': 4143,
 'remain': 6895,
 'unbeaten': 8555,
 'bytom': 1599,
 'vanhaaren': 8735,
 'logo': 5012,
 'novemb': 5895,
 '20': 176,
 '2022': 204,
 '59': 359,
 'share': 7433,
 'ann': 809,
 'arbor': 882,
 'mich': 5372,
 '17': 131,
 '16': 110,
 'fourth': 3419,
 'quarter': 6668,
 'onli': 5992,
 'second': 7338,
 'saturday': 7251,
 'senior': 7371,
 'kicker': 4662,
 'jake': 4425,
 'moodi': 5557,
 'ran': 6729,
 'field': 3274,
 'kick': 4661,
 'hi': 3949,
 'colleg': 1983,
 'career': 1667,
 'stadium': 7785,
 'game': 3526,
 'win': 9019,
 'goal': 3631,
 'entir': 2986,
 'line': 4951,
 '35': 300,
 'yarder': 9135,
 'right': 7023,
 'hash': 3861,
 'straight': 7876,
 'upright': 8675,
 'undef': 8569,
 'season': 7333,
 'aliv': 693,
 '19': 145,
 'wa': 8863,
 'said': 7189,
 'hasn': 3862,
 'anoth': 817,
 'compar': 2025,
 'thi': 8255,
 'final': 3288,
 'big': 1265,
 'hous': 4050,
 'pretti': 6515,
 'magic': 5107,
 'just': 4569,
 'glad': 3612,
 'se

In [ ]:
article_train, article_test, lable_train, lable_test = train_test_split(all_features, articles_set.topic, test_size=0.1, random_state=88)
article_train.shape, article_test.shape

((138, 9234), (16, 9234))

In [ ]:
classifier = MultinomialNB()
#traning 
classifier.fit(article_train, lable_train)


MultinomialNB()

In [ ]:
art_test

96     technology
128    technology
153    technology
30         sports
68         sports
82     technology
114    technology
125    technology
137    technology
53         sports
15         sports
109    technology
111    technology
72         sports
33         sports
127    technology
Name: topic, dtype: object

In [ ]:
classifier.predict_proba(article_test)

array([[0.00000000e+000, 1.00000000e+000],
       [1.19753703e-181, 1.00000000e+000],
       [3.37800372e-302, 1.00000000e+000],
       [1.00000000e+000, 4.05801652e-180],
       [1.00000000e+000, 0.00000000e+000],
       [3.75872958e-165, 1.00000000e+000],
       [0.00000000e+000, 1.00000000e+000],
       [2.68691846e-214, 1.00000000e+000],
       [1.98857727e-266, 1.00000000e+000],
       [1.00000000e+000, 2.45721388e-115],
       [1.00000000e+000, 6.34633887e-211],
       [5.43669024e-210, 1.00000000e+000],
       [1.17129015e-003, 9.98828710e-001],
       [1.00000000e+000, 2.21923865e-166],
       [1.00000000e+000, 1.23371911e-150],
       [1.13168743e-144, 1.00000000e+000]])

In [ ]:
nr_correct = (lable_test == classifier.predict(article_test)).sum()
print(f"articles classified correctly: {nr_correct}")

nr_incorrect = lable_test.size - nr_correct
print(f"articles classified incorrectly: {nr_incorrect}")

articles classified correctly: 16
articles classified incorrectly: 0


In [ ]:
accuracy = classifier.score(article_test, lable_test)
print(f"the testing accuracy of the model is {accuracy:.2%}")

the testing accuracy of the model is 100.00%


In [ ]:
#dividing the true positives by anything that was predicted as a positive. 
#out of all sport articles classified how many were classified corectlly 
precision_score(lable_test, classifier.predict(article_test), pos_label = 'sports', average = 'binary')

1.0

In [ ]:
#recall(True Positive Rate) 
#dividing the true positives by anything that should have been predicted as positive
#out of all sport articles how many were classified as sport
recall_score(lable_test, classifier.predict(article_test), pos_label = 'sports', average = 'binary')

1.0

In [ ]:
#the balance between the precision and the recall
#2 * ( (precision*recall) / (precision + recall) )
#the 2 is wight
f1_score(lable_test, classifier.predict(article_test), pos_label = 'sports', average = 'binary')

1.0

In [ ]:
#creating the confusion matrix
confusion_matrix(lable_test, classifier.predict(article_test), labels = ['sports', 'technology'], )

array([[ 6,  0],
       [ 0, 10]], dtype=int64)

In [ ]:
example = ["Carmaker Jaguar Land Rover (JLR) is reducing output at its factories in Solihull and Halewood until the spring, due to ongoing problems obtaining enough computer chips for new vehicles. The action is expected to affect the output of models such as the Jaguar F-Pace and Land Rover Discovery Sport. The move is understood to be temporary, as first reported in the Guardian. In the meantime, JLR will focus on more profitable models such as the Range Rover. Output of these cars has been ramped up in recent months. JLR\'s factory in Nitra, Slovakia, is not affected. Modern cars are heavily reliant on computer chips to control a variety of onboard systems, ranging from anti-lock braking and emissions controls to satellite navigation and in-car entertainment.",
"Adidas has launched an investigation into reports that rapper Kanye West created a \"toxic environment\" when he was working with the brand. Rolling Stone reported claims from some workers on the Yeezy collaboration, saying he showed them explicit pictures and videos as part of bullying tactics. In a letter, they said bosses were aware of West's \"problematic behaviour\" but \"turned their moral compass off\". Adidas said it did not yet know whether the allegations have any merit. \"It is currently not clear whether the accusations made in an anonymous letter are true,\" the company said in a statement on Thursday.",
"Crossing the finish line, scoring the goal, sticking the landing – sports can bring unforgettable moments to the lives of athletes. However, there is a lot of work required before reaching those exciting milestones. Our Sports medicine experts are here to support you every step, basket, flip or pirouette of the way. Whether you’re an athlete, an athletic coach or a parent of an athlete, we have sports advice to help you succeed. From nutrition that will help fuel you for the game to information on how to treat concussions, our sports medicine experts are here to help.",
"Cybercrime insurance is making the ransomware problem worse During the COVID-19 pandemic, there was another outbreak in cyberspace: a digital epidemic driven by ransomware. Several organisations worldwide fell victim to cyber-extortionists who stole data either to sell to other criminals or held it as a ransom for a profit. The sheer number of attacks indicates that cyber security and anti-ransomware defences did not work or have limited effectiveness."
]

In [ ]:
doc_tern_matix = vectorizer.transform(example)
classifier.predict(doc_tern_matix), classifier.predict_proba(doc_tern_matix)

(array(['technology', 'sports', 'sports', 'technology'], dtype='<U10'),
 array([[1.71582537e-05, 9.99982842e-01],
        [9.97592003e-01, 2.40799707e-03],
        [9.94406565e-01, 5.59343524e-03],
        [1.25721157e-05, 9.99987428e-01]]))